<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yiic message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE, this file must be saved in UTF-8 encoding.
 */
return array (
  'About' => '',
  'Activate your Account' => '',
  'An administrator at {{blog}} has invited you to collaborate at their site at {{site}}. To accept this invitation and to setup your account, click the following link {{link}}.' => '',
  'Authenticate' => '',
  'Awaiting activation for {{email}}. {{resend}}' => '',
  'By {{author}} under {{category}}' => '',
  'Change Your Email Address' => '',
  'Change Your Information' => '',
  'Change Your Password' => '',
  'Create Your Account' => '',
  'Create a new Account' => '',
  'Did you forget your password? Enter your email address below and we\'ll send you an email link that will allow you to reset your password.' => '',
  'Display Name' => '',
  'Email Address' => '',
  'Enter Your Current Password' => '',
  'Enter the password you registered with to activate your account.' => '',
  'Enter your current password to change your email address.' => '',
  'Enter your current password to make any changes to your account' => '',
  'Enter your new password twice to reset your password.' => '',
  'Error {{code}}' => '',
  'First Name' => '',
  'Forgot Your Password?' => '',
  'Heads Up!' => '',
  'Hello,' => '',
  'If you do not wish to accept this invite, you may safely disregard this email.' => '',
  'Last Name' => '',
  'Login to Your Account' => '',
  'No Results Found' => '',
  'Or register with one of these social networks' => '',
  'Or sign in with one of these social networks' => '',
  'P.S. If you did not request this email, you may safely ignore it.' => '',
  'Password' => '',
  'Password Required!' => '',
  'Proudly Published with {{CiiMS}} - {{Spectre}}' => '',
  'Read more' => '',
  'Recent Comments' => '',
  'Recent Posts' => '',
  'Registered' => '',
  'Reputation' => '',
  'Resend?' => '',
  'Reset Your Password' => '',
  'Search' => '',
  'Sorry, we tried looking but we didn\'t find a match for the specified criteria. Try refining your search.' => '',
  'Submit' => '',
  'Thank You,' => '',
  'Thank you.' => '',
  'Thanks for Activating Your Account!' => '',
  'Thanks for registering your account at CiiMS Blog {{blog}}. To verify your account, {{clickhere}}. This action will verify your email address and allow you to interact with features only available to registered users.' => '',
  'This Post Requires a Password to View' => '',
  'This is a notification that a request to change your email address was made on {{name}}. To approve this change, please visit {{link}}' => '',
  'This is a notification that your password has been changed on {{name}}' => '',
  'This user has not provided any information for themselves.' => '',
  'To accept your invitation, set your account details here.' => '',
  'Type to search, then press enter' => '',
  'Update Your Profile' => '',
  'Woah!' => '',
  'You may now {{login}} and head to the {{dashboard}}' => '',
  'You recently notified us that you forgot your password for the following blog: {{blog}}. To reset your password, {{clickhere}} and follow the instructions on the reset page. This link is valid for 15 minutes.' => '',
  'click here' => '',
  'dashboard' => '',
  'edit' => '',
  'forgot' => '',
  'login' => '',
  'logout' => '',
  'register' => '',
  '{{headsup}} Looks like you\'re already logged in as {{email}}' => '',
  '{{headsup}} Looks like you\'re already logged in as {{email}}. You should {{logout}} before logging in to another account.' => '',
  '{{woah}} It looks like there aren\'t any posts in this category yet. Why don\'t you check out some of our other pages or check back later?' => '',
);
